### ISSUE TITLE
customize dictionary 

### ISSUE THREAD

**Issue by niranjan8129** [sinaahmadi/RNN#1]
Can we feed customize word like?

wrong    --------------- correct
G#$oogle ------------ Google
.Du*9Bai ------------- Dubai

**Comment by sinaahmadi** [comment]
To be able to feed, in practice yes, but will the trained model will be tractable? That depends on your dataset. 
You can consider training the model with a specific dataset containing that kind of anomaly. However, in the real-life cases, those type of errors occur rarely.
